import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner"
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="pt-[72px]">
          {children}
          <Footer />
        </main>
        <Toaster richColors closeButton />
      </body>
    </html>
  )
}