import type { Metadata } from "next"
import "./globals.css"
import { Toaster } from "sonner"
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <body className="flex flex-col min-h-screen">
        <Navbar />
        <main className="flex-1 pt-[72px]">{children}</main>
        <Footer />
        <Toaster richColors closeButton />
      </body>
    </html>
  )
}
